site_name: BetonQuest
site_author: BetonQuest Organisation
site_url: https://betonquest.github.io/BetonQuest/
site_dir: target/documentation
docs_dir: documentation
repo_name: BetonQuest on GitHub
edit_uri: /BetonQuest/BetonQuest/edit/master/documentation/
repo_url: https://github.com/BetonQuest/BetonQuest
copyright: '© 2020  BetonQuest Organisation. GPLv3'


extra_css:
  - 'webCode/css/superFences.css'
  - 'webCode/css/centered.css'
  - 'webCode/css/contentAreaFullWidth.css'
  - 'webCode/css/admonition.css'
  - 'webCode/css/button.css'

extra_javascript:
  - 'webCode/js/copyLinkToClipboard.js'

# More info on this theme: https://squidfunk.github.io/mkdocs-material
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: media/design/BQIcon1k.png
  favicon: media/design/favicon.ico



# See the following for docs on these extensions: https://squidfunk.github.io/mkdocs-material/extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: 🔗

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rK6mfHq
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/betonquest
    - icon: fontawesome/brands/github
      link: https://github.com/BetonQuest/BetonQuest
    - icon: fontawesome/solid/archive
      link: https://betonquest.org/old
    - icon: fontawesome/solid/faucet
      link: https://spigotmc.org/resources/betonquest.2117/

#Notice that here are a few strange looking hairspaces in here. They make the space between the emojis and the text look equal
nav:
  - '🚀 Home':
      - '👋 Welcome!': index.md
      - 'Overview':
          - '✨ Features': Home/Features.md
          - '👔  For Owners': Home/For-Owners.md
          - '🎨 For Questers': Home/For-Questers.md
      - '💲 Sponsorships': Home/Sponsorships.md
  - '🎓 Tutorials':
      - '👋 Welcome!': Tutorials/Welcome.md
      - 'Getting Started':
          - '💻 Setting up a local test server': Tutorials/Getting-Started/Setting-up-a-local-test-server.md
          - '📥 Installing BetonQuest': Tutorials/Getting-Started/Installing-BetonQuest.md
          - '✒️ Setting up the editor': Tutorials/Getting-Started/Setting-up-the-editor.md
          - '📑 YAML for questers': Tutorials/Getting-Started/YAML-for-questers.md
          - '⏱️   Quick Start Tutorial': Tutorials/Getting-Started/Quick-Start-Tutorial.md
      - '❓ Frequently Asked Questions':
          - '🤔  General FAQ': Tutorials/Frequently-Asked-Questions.md
  - '📚 Documentation':
      - 'General':
          - '📚   Reference': Documentation/Reference.md
          - '💬  Conversations': Documentation/Conversations.md
          - '   📱     Menus': Documentation/Menus.md
      - 'Types':
          - '✔️ Objectives List': Documentation/Objectives-List.md
          - '⚙️ Events List': Documentation/Events-List.md
          - '  ❓    Conditions List': Documentation/Conditions-List.md
          - '🤝 Compatibility List': Documentation/Compatibility.md
          - '🔮   Variables List': Documentation/Variables-List.md
      - 'Notifications':
          - '🔊   Settings': Documentation/Notification-Settings.md
          - "🏷️   IO's & Categories": Documentation/Notification-IO's-&-Categories.md
      - 'Technical':
          - '🔒 Permissions & Commands': Documentation/Commands-and-permissions.md
          - '📥 Updating': Documentation/Updating-and-Backups.md
          - '🔧  Configuration': Documentation/Configuration.md
          - '🗃️ Changelog': Documentation/CHANGELOG.md
  - '🔌 API':
      - '⚙️ API': API/API.md
  - '🧪 Participate':
      - '🤝 Overview': Participate/Overview.md
      - '📰 Setup IDE': Participate/SetupIDE.md
      - 'Code':
          - '📚 Contributing Guidelines': Participate/Code/Contributing-Guidelines.md
          - '🏭 Releasing': Participate/Code/Releasing.md
          - '🏷️ Versioning': Participate/Code/Versioning.md
      - 'Docs':
          - '🔧 Setup': Participate/Docs/Setup.md
          - '📚 Guidelines': Participate/Docs/Guidelines.md

google_analytics:
  - UA-164568470-1
  - auto
